// Void elements that never have children and do not need a closing tag.
// https://html.spec.whatwg.org/multipage/syntax.html#void-elements
export const SELF_CLOSING_TAGS = new Set([
	"area",
	"base",
	"br",
	"col",
	"embed",
	"hr",
	"img",
	"input",
	"link",
	"meta",
	"param",
	"source",
	"track",
	"wbr",
]);

// HTML attribute names (lower-cased) mapped to their React prop equivalents.
// Keys are kept lower-cased so lookups can normalise the source casing first.
export const HTML_TO_REACT_ATTRS: Record<string, string> = {
	"accept-charset": "acceptCharset",
	accesskey: "accessKey",
	allowfullscreen: "allowFullScreen",
	autocapitalize: "autoCapitalize",
	autocomplete: "autoComplete",
	autocorrect: "autoCorrect",
	autofocus: "autoFocus",
	autoplay: "autoPlay",
	autosave: "autoSave",
	cellpadding: "cellPadding",
	cellspacing: "cellSpacing",
	charset: "charSet",
	class: "className",
	classid: "classID",
	colspan: "colSpan",
	contenteditable: "contentEditable",
	contextmenu: "contextMenu",
	controlslist: "controlsList",
	crossorigin: "crossOrigin",
	datetime: "dateTime",
	enctype: "encType",
	enterkeyhint: "enterKeyHint",
	for: "htmlFor",
	formaction: "formAction",
	formenctype: "formEncType",
	formmethod: "formMethod",
	formnovalidate: "formNoValidate",
	formtarget: "formTarget",
	frameborder: "frameBorder",
	hreflang: "hrefLang",
	"http-equiv": "httpEquiv",
	imagesizes: "imageSizes",
	imagesrcset: "imageSrcSet",
	inputmode: "inputMode",
	ismap: "isMap",
	itemid: "itemID",
	itemprop: "itemProp",
	itemref: "itemRef",
	itemscope: "itemScope",
	itemtype: "itemType",
	marginheight: "marginHeight",
	marginwidth: "marginWidth",
	maxlength: "maxLength",
	minlength: "minLength",
	nomodule: "noModule",
	novalidate: "noValidate",
	playsinline: "playsInline",
	radiogroup: "radioGroup",
	readonly: "readOnly",
	referrerpolicy: "referrerPolicy",
	rowspan: "rowSpan",
	spellcheck: "spellCheck",
	srcdoc: "srcDoc",
	srclang: "srcLang",
	srcset: "srcSet",
	tabindex: "tabIndex",
	usemap: "useMap",
};

// HTML boolean attributes (lower-cased). When present they map to `true`,
// regardless of their literal value, except for an explicit "false".
// https://html.spec.whatwg.org/multipage/indices.html#attributes-3
export const HTML_BOOLEAN_ATTRIBUTES = new Set([
	"allowfullscreen",
	"async",
	"autofocus",
	"autoplay",
	"checked",
	"controls",
	"default",
	"defer",
	"disabled",
	"formnovalidate",
	"hidden",
	"inert",
	"ismap",
	"itemscope",
	"loop",
	"multiple",
	"muted",
	"nomodule",
	"novalidate",
	"open",
	"playsinline",
	"readonly",
	"required",
	"reversed",
	"selected",
]);

// Named HTML character references decoded back to their literal characters.
// Numeric references (&#NN; / &#xHH;) are handled programmatically.
export const HTML_NAMED_ENTITIES: Record<string, string> = {
	amp: "&",
	apos: "'",
	bull: "•",
	cent: "¢",
	copy: "©",
	dagger: "†",
	Dagger: "‡",
	deg: "°",
	divide: "÷",
	euro: "€",
	frac12: "½",
	frac14: "¼",
	frac34: "¾",
	gt: ">",
	hellip: "…",
	iexcl: "¡",
	iquest: "¿",
	laquo: "«",
	ldquo: "“",
	lsquo: "‘",
	lt: "<",
	mdash: "—",
	middot: "·",
	nbsp: " ",
	ndash: "–",
	para: "¶",
	plusmn: "±",
	pound: "£",
	quot: '"',
	raquo: "»",
	rdquo: "”",
	reg: "®",
	rsquo: "’",
	sect: "§",
	times: "×",
	trade: "™",
	yen: "¥",
};
